project:
  type: default
  output-dir: docs

format:
  revealjs:
    theme: default
    transition: fade           # none | fade | slide | convex | concave | zoom
    background-transition: fade
    transition-speed: slow     # default | fast | slow
